### ISSUE TITLE
Cucumber-js version 2.0 compatibility

### ISSUE THREAD

**Issue by StephenDavidson** [allure-framework/allure-cucumberjs#10]
cucumber-js team is iterating through release candidates of version 2.0 of cucumber. It changes the step implementation and the allure reporter needs to be updated accordingly (or a new version needs to be spun off)

**Comment by AlexMurphy** [comment]
+1

**Comment by asidarovich** [comment]
+1

**Comment by avdynut** [comment]
+1

**Comment by slonya4ka** [comment]
+1

**Comment by baev** [comment]
https://github.com/allure-framework/allure-java/pull/155

**Comment by sebastienalonzo** [comment]
+1
Any plan to support CucumberJS 2.0 or 3.0 ?

**Comment by just-boris** [comment]
None of Allure team members is using CucumberJS at work. Therefore, we have no people, who can actually do that.

So, this issue is waiting for contributors.

**Comment by ramezsw** [comment]
+1

**Comment by michaelBurko** [comment]
+1

**Comment by JennyGr** [comment]
Is there any progress on this matter? Will someone put an effort on updating this or we should abandon the idea of using Allure with CucumberJS?

**Comment by Lastrellik** [comment]
What kind of effort are we looking at to add support? Is it not being done because it's difficult or only because nobody is using it? Our company is considering contributing to fix this.
