### ISSUE TITLE
Failed parsing stats for Allure reporter: attribute value for name 'value' should be a primitive.

### ISSUE THREAD

**Issue by nicolasgz** [allure-framework/allure-cucumberjs#13]
After executing my Cucumberjs Scenarios, I've got the following 

Failed parsing stats for Allure reporter: attribute value for name 'value' should be a primitive (string, number, boolean, null, or undefined). Dumped this.baseReporter.stats to /Users/nicolasgonzalez/qa/training-qa-java-script/allure-reporter-debug.log.
Error: attribute value for name 'value' should be a primitive (string, number, boolean, null, or undefined)
    at parseAttribute (/Users/nicolasgonzalez/qa/training-qa-java-script/node_modules/js2xmlparser/lib/main.js:76:15)

I debugged, and saw we are sending to the js2xmlparser an array instead of a primitive value. This array contains the path of the feature being run.

Can anyone give me a hand on this ?

Thanks a lot.

**Comment by ckurban** [comment]
I have the same issue, any one looking at it?
