### ISSUE TITLE
xml files not generated due to outdated "graceful-fs v3.0.8" module

### ISSUE THREAD

**Issue by igniteram** [allure-framework/allure-cucumberjs#3]
Please update the "fs-extra" module in which there is an outdated graceful-fs v3.0.8 module due to which the allure reports are not generated.
I checked and updated to graceful-fs v4.1.4 and the xml files were generated. I could send a PR if needed?
Please find the screenshot:
<img width="1418" alt="screen shot 2016-05-31 at 7 08 03 pm" src="https://cloud.githubusercontent.com/assets/15998104/15676337/6ef4a232-2763-11e6-9cee-b24b69df662c.png">

**Comment by just-boris** [comment]
Related issue: https://github.com/allure-framework/allure-jasmine-plugin/issues/9

@piociek you should update Allure-commons to 1.1.6 to avoid this warning. As I can see, there was no any incompatible changes since then.

**Comment by piociek** [comment]
working on it

**Comment by piociek** [comment]
Fixed in 1.0.1
